"""
Launch vehicle database for satellite mission planning.
Sources: publicly available data from launch provider websites, FAA launch records,
and industry publications (2024-2026).
"""

LAUNCH_VEHICLES = [
    # ── Dedicated Small Satellite Launchers ──
    {
        "name": "Rocket Lab Electron",
        "operator": "Rocket Lab",
        "country": "USA / NZ",
        "leo_capacity_kg": 300,
        "sso_capacity_kg": 200,
        "gto_capacity_kg": None,
        "cost_usd": 7_500_000,
        "lead_time_months": 12,
        "launch_cadence": "~15 per year",
        "orbits": ["LEO", "SSO"],
        "rideshare": True,
        "min_mass_kg": 1,
        "max_mass_kg": 300,
        "launch_sites": ["LC-1 Mahia (NZ)", "LC-2 Wallops (VA)"],
        "status": "Operational",
        "notes": "Dedicated small-sat launcher. Kick stage for precise orbit insertion.",
    },
    {
        "name": "Rocket Lab Neutron",
        "operator": "Rocket Lab",
        "country": "USA",
        "leo_capacity_kg": 13000,
        "sso_capacity_kg": 8000,
        "gto_capacity_kg": 1500,
        "cost_usd": 50_000_000,
        "lead_time_months": 18,
        "launch_cadence": "TBD (first launch expected 2026)",
        "orbits": ["LEO", "SSO", "GTO"],
        "rideshare": True,
        "min_mass_kg": 100,
        "max_mass_kg": 13000,
        "launch_sites": ["Wallops (VA)"],
        "status": "In development",
        "notes": "Medium-lift reusable. Designed for mega-constellation deployment.",
    },
    {
        "name": "Firefly Alpha",
        "operator": "Firefly Aerospace",
        "country": "USA",
        "leo_capacity_kg": 1030,
        "sso_capacity_kg": 630,
        "gto_capacity_kg": None,
        "cost_usd": 15_000_000,
        "lead_time_months": 12,
        "launch_cadence": "~4-6 per year",
        "orbits": ["LEO", "SSO"],
        "rideshare": True,
        "min_mass_kg": 1,
        "max_mass_kg": 1030,
        "launch_sites": ["Vandenberg SFB (CA)"],
        "status": "Operational",
        "notes": "Small-to-medium launcher. Elytra kick stage available.",
    },
    {
        "name": "ABL Space RS1",
        "operator": "ABL Space Systems",
        "country": "USA",
        "leo_capacity_kg": 1350,
        "sso_capacity_kg": 1000,
        "gto_capacity_kg": None,
        "cost_usd": 12_000_000,
        "lead_time_months": 12,
        "launch_cadence": "TBD",
        "orbits": ["LEO", "SSO"],
        "rideshare": False,
        "min_mass_kg": 50,
        "max_mass_kg": 1350,
        "launch_sites": ["Pacific Spaceport (AK)", "Others TBD"],
        "status": "In development",
        "notes": "Transportable launch system. GS-0 containerized ground segment.",
    },
    {
        "name": "Virgin Orbit LauncherOne",
        "operator": "Virgin Orbit (ceased operations 2023)",
        "country": "USA",
        "leo_capacity_kg": 500,
        "sso_capacity_kg": 300,
        "gto_capacity_kg": None,
        "cost_usd": 12_000_000,
        "lead_time_months": None,
        "launch_cadence": "N/A",
        "orbits": ["LEO", "SSO"],
        "rideshare": False,
        "min_mass_kg": 1,
        "max_mass_kg": 500,
        "launch_sites": ["Air launch"],
        "status": "Ceased operations",
        "notes": "Air-launched from 747. Company ceased operations in 2023.",
    },
    # ── Medium Lift ──
    {
        "name": "SpaceX Falcon 9",
        "operator": "SpaceX",
        "country": "USA",
        "leo_capacity_kg": 22800,
        "sso_capacity_kg": 15000,
        "gto_capacity_kg": 8300,
        "cost_usd": 67_000_000,
        "lead_time_months": 18,
        "launch_cadence": "~90+ per year",
        "orbits": ["LEO", "SSO", "GTO", "GEO", "MEO", "Polar", "Heliocentric"],
        "rideshare": True,
        "min_mass_kg": 1,
        "max_mass_kg": 22800,
        "launch_sites": ["KSC LC-39A (FL)", "SLC-40 (FL)", "SLC-4E Vandenberg (CA)"],
        "status": "Operational",
        "notes": "Most-flown active rocket. Reusable first stage. Transporter rideshare program.",
    },
    {
        "name": "SpaceX Falcon Heavy",
        "operator": "SpaceX",
        "country": "USA",
        "leo_capacity_kg": 63800,
        "sso_capacity_kg": None,
        "gto_capacity_kg": 26700,
        "cost_usd": 97_000_000,
        "lead_time_months": 24,
        "launch_cadence": "~3-5 per year",
        "orbits": ["LEO", "GTO", "GEO", "Heliocentric"],
        "rideshare": False,
        "min_mass_kg": 1000,
        "max_mass_kg": 63800,
        "launch_sites": ["KSC LC-39A (FL)"],
        "status": "Operational",
        "notes": "Heavy-lift. Three Falcon 9 cores. Used for USSF, NASA, and commercial GEO missions.",
    },
    {
        "name": "SpaceX Starship",
        "operator": "SpaceX",
        "country": "USA",
        "leo_capacity_kg": 150000,
        "sso_capacity_kg": None,
        "gto_capacity_kg": 21000,
        "cost_usd": None,
        "lead_time_months": None,
        "launch_cadence": "TBD (in flight testing)",
        "orbits": ["LEO", "GTO", "GEO", "Lunar", "Mars"],
        "rideshare": True,
        "min_mass_kg": 100,
        "max_mass_kg": 150000,
        "launch_sites": ["Starbase Boca Chica (TX)", "KSC LC-39A (FL)"],
        "status": "In development / flight testing",
        "notes": "Super heavy-lift fully reusable. Enormous payload volume.",
    },
    # ── European ──
    {
        "name": "Ariane 6 (A62)",
        "operator": "Arianespace",
        "country": "Europe (ESA)",
        "leo_capacity_kg": 10350,
        "sso_capacity_kg": 6400,
        "gto_capacity_kg": 4500,
        "cost_usd": 77_000_000,
        "lead_time_months": 24,
        "launch_cadence": "~6-9 per year (ramping up)",
        "orbits": ["LEO", "SSO", "GTO", "MEO"],
        "rideshare": True,
        "min_mass_kg": 50,
        "max_mass_kg": 10350,
        "launch_sites": ["CSG ELA-4 Kourou (French Guiana)"],
        "status": "Operational (first flight 2024)",
        "notes": "Two solid boosters. Successor to Ariane 5.",
    },
    {
        "name": "Ariane 6 (A64)",
        "operator": "Arianespace",
        "country": "Europe (ESA)",
        "leo_capacity_kg": 21650,
        "sso_capacity_kg": None,
        "gto_capacity_kg": 11500,
        "cost_usd": 115_000_000,
        "lead_time_months": 24,
        "launch_cadence": "~3-4 per year",
        "orbits": ["LEO", "SSO", "GTO", "GEO"],
        "rideshare": True,
        "min_mass_kg": 500,
        "max_mass_kg": 21650,
        "launch_sites": ["CSG ELA-4 Kourou (French Guiana)"],
        "status": "Operational",
        "notes": "Four solid boosters. Heavy configuration for GTO/GEO missions.",
    },
    {
        "name": "Vega-C",
        "operator": "Arianespace",
        "country": "Europe (ESA)",
        "leo_capacity_kg": 2300,
        "sso_capacity_kg": 1500,
        "gto_capacity_kg": None,
        "cost_usd": 37_000_000,
        "lead_time_months": 18,
        "launch_cadence": "~3-4 per year",
        "orbits": ["LEO", "SSO", "Polar"],
        "rideshare": True,
        "min_mass_kg": 1,
        "max_mass_kg": 2300,
        "launch_sites": ["CSG ZLV Kourou (French Guiana)"],
        "status": "Operational (return to flight 2024)",
        "notes": "Light-medium launcher. SSMS rideshare dispenser available.",
    },
    # ── Indian ──
    {
        "name": "ISRO PSLV",
        "operator": "ISRO / NSIL",
        "country": "India",
        "leo_capacity_kg": 3800,
        "sso_capacity_kg": 1750,
        "gto_capacity_kg": 1425,
        "cost_usd": 28_000_000,
        "lead_time_months": 18,
        "launch_cadence": "~6-8 per year",
        "orbits": ["LEO", "SSO", "GTO", "Polar"],
        "rideshare": True,
        "min_mass_kg": 1,
        "max_mass_kg": 3800,
        "launch_sites": ["SDSC SHAR Sriharikota (India)"],
        "status": "Operational",
        "notes": "Workhorse launcher. Extensive rideshare experience (104 sats on single launch).",
    },
    {
        "name": "ISRO GSLV Mk III (LVM3)",
        "operator": "ISRO / NSIL",
        "country": "India",
        "leo_capacity_kg": 10000,
        "sso_capacity_kg": None,
        "gto_capacity_kg": 4000,
        "cost_usd": 50_000_000,
        "lead_time_months": 24,
        "launch_cadence": "~2-3 per year",
        "orbits": ["LEO", "GTO", "GEO"],
        "rideshare": False,
        "min_mass_kg": 500,
        "max_mass_kg": 10000,
        "launch_sites": ["SDSC SHAR Sriharikota (India)"],
        "status": "Operational",
        "notes": "Heavy-lift. Used for Chandrayaan-3 and OneWeb constellation.",
    },
    {
        "name": "ISRO SSLV",
        "operator": "ISRO / NSIL",
        "country": "India",
        "leo_capacity_kg": 500,
        "sso_capacity_kg": 300,
        "gto_capacity_kg": None,
        "cost_usd": 6_000_000,
        "lead_time_months": 6,
        "launch_cadence": "~6+ per year (ramping)",
        "orbits": ["LEO", "SSO"],
        "rideshare": True,
        "min_mass_kg": 1,
        "max_mass_kg": 500,
        "launch_sites": ["SDSC SHAR Sriharikota (India)"],
        "status": "Operational",
        "notes": "Small satellite launch vehicle. Very low cost, rapid turnaround.",
    },
    # ── Japanese ──
    {
        "name": "JAXA H3",
        "operator": "JAXA / MHI",
        "country": "Japan",
        "leo_capacity_kg": 16500,
        "sso_capacity_kg": 9000,
        "gto_capacity_kg": 6500,
        "cost_usd": 50_000_000,
        "lead_time_months": 24,
        "launch_cadence": "~4-6 per year",
        "orbits": ["LEO", "SSO", "GTO", "GEO"],
        "rideshare": True,
        "min_mass_kg": 100,
        "max_mass_kg": 16500,
        "launch_sites": ["Tanegashima Space Center (Japan)"],
        "status": "Operational (first success 2024)",
        "notes": "Successor to H-IIA. Multiple configurations (H3-22, H3-24, H3-30).",
    },
    {
        "name": "Epsilon S",
        "operator": "JAXA / IHI Aerospace",
        "country": "Japan",
        "leo_capacity_kg": 1400,
        "sso_capacity_kg": 600,
        "gto_capacity_kg": None,
        "cost_usd": 30_000_000,
        "lead_time_months": 18,
        "launch_cadence": "~1-2 per year",
        "orbits": ["LEO", "SSO"],
        "rideshare": True,
        "min_mass_kg": 1,
        "max_mass_kg": 1400,
        "launch_sites": ["Uchinoura Space Center (Japan)"],
        "status": "In development (return after failure)",
        "notes": "Solid-fuel small launcher.",
    },
    # ── Chinese ──
    {
        "name": "Long March 2D",
        "operator": "CASC",
        "country": "China",
        "leo_capacity_kg": 3500,
        "sso_capacity_kg": 1300,
        "gto_capacity_kg": None,
        "cost_usd": 25_000_000,
        "lead_time_months": 18,
        "launch_cadence": "~10+ per year",
        "orbits": ["LEO", "SSO"],
        "rideshare": True,
        "min_mass_kg": 1,
        "max_mass_kg": 3500,
        "launch_sites": ["Jiuquan (China)", "Xichang (China)"],
        "status": "Operational",
        "notes": "Reliable workhorse. Note: ITAR restrictions may apply for US payloads.",
    },
    {
        "name": "Long March 5",
        "operator": "CASC",
        "country": "China",
        "leo_capacity_kg": 25000,
        "sso_capacity_kg": None,
        "gto_capacity_kg": 14000,
        "cost_usd": 100_000_000,
        "lead_time_months": 24,
        "launch_cadence": "~2-3 per year",
        "orbits": ["LEO", "GTO", "GEO", "Lunar"],
        "rideshare": False,
        "min_mass_kg": 1000,
        "max_mass_kg": 25000,
        "launch_sites": ["Wenchang (China)"],
        "status": "Operational",
        "notes": "Heavy-lift. ITAR restrictions apply for US payloads.",
    },
    # ── Rideshare Programs ──
    {
        "name": "SpaceX Transporter (Rideshare)",
        "operator": "SpaceX",
        "country": "USA",
        "leo_capacity_kg": 200,
        "sso_capacity_kg": 200,
        "gto_capacity_kg": None,
        "cost_usd": 1_100_000,
        "lead_time_months": 6,
        "launch_cadence": "~4-6 per year",
        "orbits": ["SSO"],
        "rideshare": True,
        "min_mass_kg": 1,
        "max_mass_kg": 200,
        "launch_sites": ["Vandenberg SFB (CA)", "Cape Canaveral (FL)"],
        "status": "Operational",
        "notes": "Starting at $1.1M for 200 kg to SSO. Uses Falcon 9. Most affordable rideshare.",
    },
    {
        "name": "D-Orbit ION (Orbital Transfer)",
        "operator": "D-Orbit",
        "country": "Italy",
        "leo_capacity_kg": 150,
        "sso_capacity_kg": 150,
        "gto_capacity_kg": None,
        "cost_usd": 500_000,
        "lead_time_months": 6,
        "launch_cadence": "~4-6 per year",
        "orbits": ["LEO", "SSO"],
        "rideshare": True,
        "min_mass_kg": 1,
        "max_mass_kg": 150,
        "launch_sites": ["Various (rides on Falcon 9, Vega-C, etc.)"],
        "status": "Operational",
        "notes": "Last-mile delivery vehicle. Deploys smallsats to precise orbits from rideshare.",
    },
    {
        "name": "Exolaunch (Rideshare Deployer)",
        "operator": "Exolaunch",
        "country": "Germany",
        "leo_capacity_kg": 150,
        "sso_capacity_kg": 150,
        "gto_capacity_kg": None,
        "cost_usd": 600_000,
        "lead_time_months": 6,
        "launch_cadence": "~6+ per year",
        "orbits": ["LEO", "SSO"],
        "rideshare": True,
        "min_mass_kg": 1,
        "max_mass_kg": 150,
        "launch_sites": ["Various (primarily Falcon 9 Transporter)"],
        "status": "Operational",
        "notes": "Rideshare integration & deployment services. 300+ sats deployed.",
    },
    # ── Other ──
    {
        "name": "ULA Vulcan Centaur",
        "operator": "United Launch Alliance",
        "country": "USA",
        "leo_capacity_kg": 27200,
        "sso_capacity_kg": None,
        "gto_capacity_kg": 10600,
        "cost_usd": 110_000_000,
        "lead_time_months": 24,
        "launch_cadence": "~6-8 per year (ramping)",
        "orbits": ["LEO", "SSO", "GTO", "GEO", "MEO"],
        "rideshare": False,
        "min_mass_kg": 500,
        "max_mass_kg": 27200,
        "launch_sites": ["SLC-41 Cape Canaveral (FL)"],
        "status": "Operational (first flight 2024)",
        "notes": "Successor to Atlas V and Delta IV. NSSL certified.",
    },
    {
        "name": "Blue Origin New Glenn",
        "operator": "Blue Origin",
        "country": "USA",
        "leo_capacity_kg": 45000,
        "sso_capacity_kg": None,
        "gto_capacity_kg": 13600,
        "cost_usd": 68_000_000,
        "lead_time_months": 24,
        "launch_cadence": "TBD (first flight 2025)",
        "orbits": ["LEO", "GTO", "GEO"],
        "rideshare": True,
        "min_mass_kg": 500,
        "max_mass_kg": 45000,
        "launch_sites": ["LC-36 Cape Canaveral (FL)"],
        "status": "In development (first flight 2025)",
        "notes": "Heavy-lift reusable. BE-4 engines. 7-meter fairing.",
    },
    {
        "name": "Relativity Space Terran R",
        "operator": "Relativity Space",
        "country": "USA",
        "leo_capacity_kg": 20000,
        "sso_capacity_kg": None,
        "gto_capacity_kg": 5000,
        "cost_usd": None,
        "lead_time_months": None,
        "launch_cadence": "TBD",
        "orbits": ["LEO", "SSO", "GTO"],
        "rideshare": True,
        "min_mass_kg": 100,
        "max_mass_kg": 20000,
        "launch_sites": ["Cape Canaveral (FL)"],
        "status": "In development",
        "notes": "3D-printed reusable medium-lift. Largely 3D printed structure.",
    },
]


def find_compatible_vehicles(mass_kg: float, orbit_type: str, satellite_class: str = "") -> list:
    """Find launch vehicles compatible with given mass and orbit requirements."""
    results = []
    orbit_upper = orbit_type.upper()

    for v in LAUNCH_VEHICLES:
        if v["status"] == "Ceased operations":
            continue

        orbit_match = False
        for supported in v["orbits"]:
            if supported.upper() in orbit_upper or orbit_upper in supported.upper():
                orbit_match = True
                break
        if "LEO" in orbit_upper or "SSO" in orbit_upper:
            if "LEO" in v["orbits"] or "SSO" in v["orbits"]:
                orbit_match = True
        if "GEO" in orbit_upper or "GTO" in orbit_upper:
            if "GTO" in v["orbits"] or "GEO" in v["orbits"]:
                orbit_match = True

        if not orbit_match:
            continue

        if "SSO" in orbit_upper and v.get("sso_capacity_kg"):
            capacity = v["sso_capacity_kg"]
        elif "GTO" in orbit_upper and v.get("gto_capacity_kg"):
            capacity = v["gto_capacity_kg"]
        elif "GEO" in orbit_upper and v.get("gto_capacity_kg"):
            capacity = v["gto_capacity_kg"]
        else:
            capacity = v["leo_capacity_kg"]

        if capacity and mass_kg <= capacity:
            margin = (capacity - mass_kg) / capacity * 100
            results.append({
                **v,
                "capacity_for_orbit": capacity,
                "mass_margin_pct": margin,
            })

    results.sort(key=lambda x: (
        0 if x["status"] == "Operational" else 1,
        abs(x["capacity_for_orbit"] - mass_kg * 2),
    ))

    return results
